// ==UserScript==
// @name         Torn OC CRP Fit
// @namespace    http://tampermonkey.net/
// @version      1.2
// @description  Highlights the organised crime slots that best fit your CPR, using the faction CRP/weight table.
// @match        https://www.torn.com/factions.php?step=your&type=1*
// @grant        GM_registerMenuCommand
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_xmlhttpRequest
// @grant        GM_addStyle
// @homepageURL  https://github.com/xDp64xG/Torn-Intel
// @supportURL   https://github.com/xDp64xG/Torn-Intel/issues
// @connect      raw.githubusercontent.com
// @updateURL    https://raw.githubusercontent.com/xDp64xG/Torn-Intel/main/scripts/tampermonkey/Torn%20OC%20CRP%20Fit.user.js
// @downloadURL  https://raw.githubusercontent.com/xDp64xG/Torn-Intel/main/scripts/tampermonkey/Torn%20OC%20CRP%20Fit.user.js
// ==/UserScript==

(function () {
  'use strict';

  const TABLE_URL_KEY = 'gts_crp_table_url';
  const TABLE_CACHE_KEY = 'gts_crp_table_cache';
  const MANUAL_CPR_KEY = 'gts_crp_manual_cpr';
  const DEBUG_KEY = 'gts_crp_debug';
  const DEFAULT_TABLE_URL =
    'https://raw.githubusercontent.com/xDp64xG/Torn-Intel/main/data/oc_crp_table.json';
  const SLOT_HINTS = '.tt-oc-highlight, [class*="waitingJoin"]';
  const CRIME_LIST = '#faction-crimes-root';
  const OVERLAY_ID = 'crp-overlay';
  const RESCAN_MS = 1200;

  let table = null;
  let crimesByName = new Map();
  let manualCpr = Number(GM_getValue(MANUAL_CPR_KEY, 0)) || 0;
  let debug = GM_getValue(DEBUG_KEY, false);

  /* BEGIN EMBEDDED TABLE (generated by scripts/build_oc_crp_table.py) */
  const EMBEDDED_TABLE = {"source":"OC CRP Table.xlsx","weight_bands":[{"label":"Very Low","min_weight":0.0,"min_cpr":40},{"label":"Low","min_weight":0.05,"min_cpr":65},{"label":"Standard","min_weight":0.15,"min_cpr":70},{"label":"High","min_weight":0.25,"min_cpr":75}],"tier_adjustments":{"8":-5,"9":-5,"10":-15},"crimes":[{"name":"Smoke and Wing Mirrors","tier":3,"success_chance":0.728,"roles":[{"position":"Car Thief","weight":0.509,"min_cpr":75},{"position":"Imitator","weight":0.2711,"min_cpr":75},{"position":"Hustler #1","weight":0.09,"min_cpr":65},{"position":"Hustler #2","weight":0.13,"min_cpr":65}]},{"name":"Market Forces","tier":3,"success_chance":0.7149,"roles":[{"position":"Enforcer","weight":0.294,"min_cpr":75},{"position":"Negotiator","weight":0.2723,"min_cpr":75},{"position":"Lookout","weight":0.1637,"min_cpr":70},{"position":"Arsonist","weight":0.0446,"min_cpr":40},{"position":"Muscle","weight":0.2255,"min_cpr":70}]},{"name":"Gaslight the Way","tier":3,"success_chance":0.7188,"roles":[{"position":"Imitator #1","weight":0.0939,"min_cpr":65},{"position":"Imitator #2","weight":0.2746,"min_cpr":75},{"position":"Imitator #3","weight":0.4132,"min_cpr":75},{"position":"Looter #1","weight":0.0939,"min_cpr":65},{"position":"Looter #2","weight":0.0,"min_cpr":40},{"position":"Looter #3","weight":0.1242,"min_cpr":65}]},{"name":"Snow Blind","tier":4,"success_chance":0.7331,"roles":[{"position":"Hustler","weight":0.4841,"min_cpr":75},{"position":"Imitator","weight":0.3557,"min_cpr":75},{"position":"Muscle #1","weight":0.0851,"min_cpr":65},{"position":"Muscle #2","weight":0.0851,"min_cpr":65}]},{"name":"Plucking the Lotus Petal","tier":4,"success_chance":0.7097,"roles":[{"position":"Muscle","weight":0.479,"min_cpr":75},{"position":"Hustler","weight":0.1439,"min_cpr":65},{"position":"Robber #1","weight":0.1403,"min_cpr":65},{"position":"Robber #2","weight":0.2368,"min_cpr":70}]},{"name":"Stage Fright","tier":4,"success_chance":0.7075,"roles":[{"position":"Enforcer","weight":0.1567,"min_cpr":70},{"position":"Muscle #1","weight":0.2001,"min_cpr":70},{"position":"Muscle #2","weight":0.0266,"min_cpr":40},{"position":"Muscle #3","weight":0.0917,"min_cpr":65},{"position":"Lookout","weight":0.0619,"min_cpr":65},{"position":"Sniper","weight":0.463,"min_cpr":75}]},{"name":"Guardian Angels","tier":5,"success_chance":0.75,"roles":[{"position":"Enforcer","weight":0.274,"min_cpr":75},{"position":"Hustler","weight":0.421,"min_cpr":75},{"position":"Engineer","weight":0.3049,"min_cpr":75}]},{"name":"Counter Offer","tier":5,"success_chance":0.7226,"roles":[{"position":"Robber","weight":0.3595,"min_cpr":75},{"position":"Looter","weight":0.07,"min_cpr":65},{"position":"Hacker","weight":0.1213,"min_cpr":65},{"position":"Picklock","weight":0.1654,"min_cpr":70},{"position":"Engineer","weight":0.2839,"min_cpr":75}]},{"name":"No Reserve","tier":5,"success_chance":0.75,"roles":[{"position":"Car Thief","weight":0.3051,"min_cpr":75},{"position":"Techie","weight":0.3837,"min_cpr":75},{"position":"Engineer","weight":0.3112,"min_cpr":75}]},{"name":"Honey Trap","tier":5,"success_chance":0.75,"roles":[{"position":"Muscle #1","weight":0.3087,"min_cpr":75},{"position":"Muscle #2","weight":0.4215,"min_cpr":75},{"position":"Enforcer","weight":0.2698,"min_cpr":75}]},{"name":"Bidding War","tier":6,"success_chance":0.7021,"roles":[{"position":"Bomber #1","weight":0.0785,"min_cpr":65},{"position":"Bomber #2","weight":0.1797,"min_cpr":70},{"position":"Robber #1","weight":0.071,"min_cpr":65},{"position":"Robber #2","weight":0.2287,"min_cpr":70},{"position":"Robber #3","weight":0.3167,"min_cpr":75},{"position":"Driver","weight":0.1254,"min_cpr":65}]},{"name":"Leave No Trace","tier":6,"success_chance":0.75,"roles":[{"position":"Techie","weight":0.2901,"min_cpr":75},{"position":"Negotiator","weight":0.3413,"min_cpr":75},{"position":"Imitator","weight":0.3686,"min_cpr":75}]},{"name":"Dish It Out","tier":6,"success_chance":0.7126,"roles":[{"position":"Assassin","weight":0.3734,"min_cpr":75},{"position":"Muscle","weight":0.2524,"min_cpr":75},{"position":"Saboteur #1","weight":0.1464,"min_cpr":65},{"position":"Saboteur #2","weight":0.0891,"min_cpr":65},{"position":"Engineer","weight":0.1387,"min_cpr":65}]},{"name":"Sneaky Git Grab","tier":6,"success_chance":0.7182,"roles":[{"position":"Imitator","weight":0.1754,"min_cpr":70},{"position":"Pickpocket","weight":0.5083,"min_cpr":75},{"position":"Hacker","weight":0.1448,"min_cpr":65},{"position":"Techie","weight":0.1715,"min_cpr":70}]},{"name":"Blast From The Past","tier":7,"success_chance":0.6972,"roles":[{"position":"Hacker","weight":0.1206,"min_cpr":65},{"position":"Picklock #1","weight":0.1085,"min_cpr":65},{"position":"Picklock #2","weight":0.0287,"min_cpr":40},{"position":"Engineer","weight":0.2402,"min_cpr":70},{"position":"Bomber","weight":0.1562,"min_cpr":70},{"position":"Muscle","weight":0.3459,"min_cpr":75}]},{"name":"Window of Opportunity","tier":7,"success_chance":0.7056,"roles":[{"position":"Engineer","weight":0.1455,"min_cpr":65},{"position":"Looter #1","weight":0.1954,"min_cpr":70},{"position":"Looter #2","weight":0.258,"min_cpr":75},{"position":"Muscle #1","weight":0.2309,"min_cpr":70},{"position":"Muscle #2","weight":0.1701,"min_cpr":70}]},{"name":"Break the Bank","tier":8,"success_chance":0.6549,"roles":[{"position":"Robber","weight":0.127,"min_cpr":60},{"position":"Muscle #1","weight":0.1352,"min_cpr":60},{"position":"Muscle #2","weight":0.101,"min_cpr":60},{"position":"Muscle #3","weight":0.3165,"min_cpr":70},{"position":"Thief #1","weight":0.0293,"min_cpr":40},{"position":"Thief #2","weight":0.291,"min_cpr":70}]},{"name":"Clinical Precision","tier":8,"success_chance":0.6717,"roles":[{"position":"Assassin","weight":0.1606,"min_cpr":65},{"position":"Cat Burglar","weight":0.1894,"min_cpr":65},{"position":"Cleaner","weight":0.2169,"min_cpr":65},{"position":"Imitator","weight":0.4332,"min_cpr":70}]},{"name":"Stacking the Deck","tier":8,"success_chance":0.6794,"roles":[{"position":"Cat Burglar","weight":0.2343,"min_cpr":65},{"position":"Driver","weight":0.0296,"min_cpr":40},{"position":"Hacker","weight":0.2544,"min_cpr":70},{"position":"Imitator","weight":0.4817,"min_cpr":70}]},{"name":"Lock Stock","tier":8,"success_chance":0.6587,"roles":[{"position":"Assassin","weight":0.3859,"min_cpr":70},{"position":"Smuggler","weight":0.2495,"min_cpr":65},{"position":"Hacker","weight":0.1535,"min_cpr":65},{"position":"Muscle #1","weight":0.1056,"min_cpr":60},{"position":"Muscle #2","weight":0.1056,"min_cpr":60}]},{"name":"Manifest Cruelty","tier":8,"success_chance":0.6662,"roles":[{"position":"Hacker","weight":0.1632,"min_cpr":65},{"position":"Interrogator","weight":0.2349,"min_cpr":65},{"position":"Reviver","weight":0.4627,"min_cpr":70},{"position":"Cat Burglar","weight":0.1391,"min_cpr":60}]},{"name":"Ace in the Hole","tier":9,"success_chance":0.6604,"roles":[{"position":"Imitator","weight":0.2108,"min_cpr":65},{"position":"Muscle #1","weight":0.183,"min_cpr":65},{"position":"Muscle #2","weight":0.2465,"min_cpr":65},{"position":"Hacker","weight":0.2834,"min_cpr":70},{"position":"Driver","weight":0.0763,"min_cpr":60}]},{"name":"Gone Fission","tier":9,"success_chance":0.6632,"roles":[{"position":"Hijacker","weight":0.2494,"min_cpr":65},{"position":"Engineer","weight":0.1557,"min_cpr":65},{"position":"Pickpocket","weight":0.1653,"min_cpr":65},{"position":"Imitator","weight":0.2694,"min_cpr":70},{"position":"Bomber","weight":0.1802,"min_cpr":65}]},{"name":"Hostile Takeover","tier":9,"success_chance":0.6438,"roles":[{"position":"Hacker","weight":0.1026,"min_cpr":60},{"position":"Engineer","weight":0.2002,"min_cpr":65},{"position":"Cat Burglar","weight":0.1703,"min_cpr":65},{"position":"Kidnapper","weight":0.1277,"min_cpr":60},{"position":"Negotiator","weight":0.2529,"min_cpr":70},{"position":"Muscle","weight":0.1463,"min_cpr":60}]},{"name":"Crane Reaction","tier":10,"success_chance":0.557,"roles":[{"position":"Sniper","weight":0.4074,"min_cpr":60},{"position":"Lookout","weight":0.1662,"min_cpr":55},{"position":"Engineer","weight":0.0829,"min_cpr":50},{"position":"Bomber","weight":0.1589,"min_cpr":55},{"position":"Muscle #1","weight":0.1068,"min_cpr":50},{"position":"Muscle #2","weight":0.0778,"min_cpr":50}]}]};
  /* END EMBEDDED TABLE */

  GM_addStyle(`
    #crp-overlay { position: absolute; top: 0; left: 0; width: 0; height: 0; z-index: 900; }
    #crp-overlay .crp-box {
      position: absolute; box-sizing: border-box; border-radius: 4px; pointer-events: none;
    }
    #crp-overlay .crp-best { border: 2px solid #4caf50; background: rgba(76,175,80,0.18); }
    #crp-overlay .crp-ok { border: 2px solid #8bc34a; }
    #crp-overlay .crp-low { border: 2px dashed #e53935; background: rgba(229,57,53,0.10); }
    #crp-overlay .crp-badge {
      position: absolute; top: 0; right: 0;
      font-size: 10px; line-height: 12px; padding: 1px 4px; border-radius: 0 3px 0 3px;
      background: rgba(0,0,0,0.85); color: #fff; white-space: nowrap;
    }
    #crp-panel {
      position: fixed; right: 12px; bottom: 12px; z-index: 9999; width: 250px;
      background: #1b1b1b; color: #eee; border: 1px solid #444; border-radius: 6px;
      font: 12px/1.4 Arial, sans-serif; padding: 8px;
    }
    #crp-panel h4 { margin: 0 0 6px; font-size: 12px; color: #8bc34a; }
    #crp-panel ol { margin: 0; padding-left: 16px; }
    #crp-panel .crp-muted { color: #999; }
  `);

  GM_registerMenuCommand('Set CRP table URL', () => {
    const url = prompt('URL of oc_crp_table.json:', tableUrl());
    if (url) {
      GM_setValue(TABLE_URL_KEY, url.trim());
      loadTable(true).then(scan);
    }
  });

  GM_registerMenuCommand('Set fallback CPR', () => {
    const value = prompt('Your CPR to use when the page does not show one (0 = off):', manualCpr);
    if (value !== null) {
      manualCpr = Number(value) || 0;
      GM_setValue(MANUAL_CPR_KEY, manualCpr);
      scan();
    }
  });

  GM_registerMenuCommand('Refresh CRP table', () => loadTable(true).then(scan));

  GM_registerMenuCommand('Toggle CRP debug logging', () => {
    debug = !debug;
    GM_setValue(DEBUG_KEY, debug);
    scan();
  });

  function log(...args) {
    if (debug) console.log('[CRP Fit]', ...args);
  }

  function tableUrl() {
    return GM_getValue(TABLE_URL_KEY, DEFAULT_TABLE_URL);
  }

  function loadTable(force) {
    const cached = parseTable(GM_getValue(TABLE_CACHE_KEY, ''));
    if (cached && !force) {
      applyTable(cached);
      return Promise.resolve(table);
    }

    applyTable(cached || EMBEDDED_TABLE);
    return new Promise(resolve => {
      GM_xmlhttpRequest({
        method: 'GET',
        url: tableUrl(),
        onload: res => {
          const data = res.status === 200 ? parseTable(res.responseText) : null;
          if (data) {
            GM_setValue(TABLE_CACHE_KEY, res.responseText);
            applyTable(data);
          } else {
            log('remote table unavailable (status', res.status, ') - using embedded copy');
          }
          resolve(table);
        },
        onerror: () => {
          log('remote table request failed - using embedded copy');
          resolve(table);
        }
      });
    });
  }

  function parseTable(text) {
    if (!text) return null;
    try {
      const data = JSON.parse(text);
      return Array.isArray(data.crimes) && data.crimes.length ? data : null;
    } catch (err) {
      return null;
    }
  }

  function applyTable(data) {
    table = data;
    crimesByName = new Map();
    (data.crimes || []).forEach(crime => {
      crimesByName.set(norm(crime.name), crime);
      crime.rolesByBase = groupRoles(crime.roles);
    });
  }

  function norm(text) {
    return (text || '').replace(/\s+/g, ' ').trim().toLowerCase();
  }

  function basePosition(position) {
    return norm(position.replace(/#\d+\s*$/, ''));
  }

  // "Muscle #1"/"Muscle #2" appear on the page as two plain "Muscle" slots,
  // so keep them ordered per base name and consume them in DOM order.
  function groupRoles(roles) {
    const grouped = new Map();
    roles.forEach(role => {
      const key = basePosition(role.position);
      if (!grouped.has(key)) grouped.set(key, []);
      grouped.get(key).push(role);
    });
    return grouped;
  }

  function leafElements(root) {
    return Array.from((root || document).querySelectorAll('div, span, p, li, h4, b'))
      .filter(el => el.children.length === 0 && el.textContent.trim().length > 0);
  }

  // A slot in a recruiting crime carries the TornTools highlight class or Torn's
  // hashed "waitingJoin" class; its parent element is the row holding every slot.
  function findSlotRows() {
    const root = document.querySelector(CRIME_LIST) || document.body;
    const rows = new Set();
    root.querySelectorAll(SLOT_HINTS).forEach(hint => {
      const row = hint.parentElement;
      if (row && row.children.length) rows.add(row);
    });
    return Array.from(rows);
  }

  function findCrimeCard(row) {
    let node = row;
    for (let depth = 0; depth < 10 && node; depth++, node = node.parentElement) {
      const crime = crimeIn(node);
      if (crime) return { card: node, crime };
    }
    return null;
  }

  function crimeIn(node) {
    for (const el of leafElements(node)) {
      const crime = crimesByName.get(norm(el.textContent));
      if (crime) return crime;
    }
    return null;
  }

  function isRecruiting(card) {
    return /recruiting|waiting|join/i.test(card.textContent);
  }

  function isEmptySlot(slot) {
    if (/waitingjoin/i.test(slot.className)) return true;
    if (slot.querySelector('a[href*="profiles.php"], a[href*="XID="]')) return false;
    return /\bjoin\b|empty|available/i.test(slot.textContent);
  }

  function positionOf(slot, crime) {
    for (const el of leafElements(slot)) {
      const key = basePosition(el.textContent);
      if (crime.rolesByBase.has(key)) return key;
    }
    const key = basePosition(slot.textContent);
    return crime.rolesByBase.has(key) ? key : null;
  }

  // Torn renders your pass rate for the position in the slot header.
  function readCpr(slot) {
    const chance = slot.querySelector('[class*="successChance"]');
    const text = chance ? chance.textContent : slot.textContent;
    const match = text.match(/(\d{1,3})\s*%/) || (chance && text.match(/(\d{1,3})/));
    if (match) return parseInt(match[1], 10);
    return manualCpr || null;
  }

  function collectSlots() {
    const results = [];

    findSlotRows().forEach(row => {
      const match = findCrimeCard(row);
      if (!match) {
        log('slot row without a known crime name', row);
        return;
      }
      const { card, crime } = match;
      if (!isRecruiting(card)) return;

      const used = new Map();
      Array.from(row.children).forEach(slot => {
        const key = positionOf(slot, crime);
        if (!key) return;

        const index = used.get(key) || 0;
        used.set(key, index + 1);
        const role = crime.rolesByBase.get(key)[index];
        if (!role || !isEmptySlot(slot)) return;

        results.push({ crime, role, slot, cpr: readCpr(slot) });
      });
    });

    log('open slots found', results.length, results);
    return results;
  }

  // Torn's React tree rewrites className on every re-render, so highlights are
  // drawn as absolutely positioned boxes in an overlay layer instead.
  let highlights = [];

  function overlayRoot() {
    let root = document.getElementById(OVERLAY_ID);
    if (!root) {
      root = document.createElement('div');
      root.id = OVERLAY_ID;
      document.body.appendChild(root);
    }
    return root;
  }

  function clearMarks() {
    highlights = [];
    const root = document.getElementById(OVERLAY_ID);
    if (root) root.innerHTML = '';
  }

  function drawHighlights() {
    const root = overlayRoot();
    root.innerHTML = '';

    highlights.forEach(entry => {
      if (!document.contains(entry.slot)) return;
      const rect = entry.slot.getBoundingClientRect();
      if (!rect.width || !rect.height) return;

      const box = document.createElement('div');
      box.className = `crp-box ${entry.kind}`;
      box.style.left = `${rect.left + window.scrollX}px`;
      box.style.top = `${rect.top + window.scrollY}px`;
      box.style.width = `${rect.width}px`;
      box.style.height = `${rect.height}px`;

      const badge = document.createElement('span');
      badge.className = 'crp-badge';
      badge.textContent = entry.label;
      box.appendChild(badge);
      root.appendChild(box);
    });
  }

  function scan() {
    if (!table || !isOcPage()) {
      clearMarks();
      const panel = document.getElementById('crp-panel');
      if (panel) panel.remove();
      return;
    }

    const evaluated = collectSlots().map(entry => {
      const eligible = entry.cpr !== null && entry.cpr >= entry.role.min_cpr;
      return Object.assign(entry, {
        eligible,
        score: eligible ? entry.role.weight * (entry.cpr / 100) : -1
      });
    });

    evaluated.sort((a, b) => b.score - a.score);
    const best = evaluated.filter(e => e.eligible).slice(0, 3);

    highlights = evaluated.map(entry => ({
      slot: entry.slot,
      kind: best[0] === entry ? 'crp-best' : entry.eligible ? 'crp-ok' : 'crp-low',
      label: `${entry.cpr}/${entry.role.min_cpr} · w ${(entry.role.weight * 100).toFixed(1)}%`
    }));

    drawHighlights();
    renderPanel(best, evaluated.length);
  }

  function renderPanel(best, total) {
    let panel = document.getElementById('crp-panel');
    if (!panel) {
      panel = document.createElement('div');
      panel.id = 'crp-panel';
      document.body.appendChild(panel);
    }

    if (!total) {
      panel.innerHTML =
        '<h4>OC CRP Fit</h4><div class="crp-muted">No open slots detected on recruiting crimes.</div>';
      return;
    }

    const items = best
      .map(
        e =>
          `<li><b>${e.crime.name}</b> — ${e.role.position}<br>` +
          `<span class="crp-muted">your ${e.cpr} / need ${e.role.min_cpr} · weight ${(e.role.weight * 100).toFixed(1)}%</span></li>`
      )
      .join('');

    panel.innerHTML =
      `<h4>OC CRP Fit — best of ${total} open slots</h4>` +
      (items ? `<ol>${items}</ol>` : '<div class="crp-muted">No open slot meets your CPR.</div>');
  }

  function isOcPage() {
    return (
      location.pathname === '/factions.php' &&
      location.search.includes('step=your') &&
      location.search.includes('type=1') &&
      location.hash.includes('tab=crimes')
    );
  }

  let timer = null;
  function schedule() {
    clearTimeout(timer);
    timer = setTimeout(scan, RESCAN_MS);
  }

  function isOurs(node) {
    return !!(node && node.closest && node.closest(`#${OVERLAY_ID}, #crp-panel`));
  }

  let frame = null;
  function reposition() {
    if (frame) return;
    frame = requestAnimationFrame(() => {
      frame = null;
      if (highlights.length) drawHighlights();
    });
  }

  loadTable(false).then(() => {
    scan();
    new MutationObserver(mutations => {
      if (mutations.every(m => isOurs(m.target))) return;
      reposition();
      schedule();
    }).observe(document.body, { childList: true, subtree: true });
    window.addEventListener('scroll', reposition, { passive: true });
    window.addEventListener('resize', reposition);
    window.addEventListener('hashchange', schedule);
  });
})();
